export const siteConfig = {
	name: "shadcn-svelte-lab",
	url: "https://shadcn-svelte.com",
	ogImage: {
		url: "https://shadcn-svelte.com/opengraph-image.png",
		width: "1200",
		height: "630",
	},
	description:
		"Documentation for shadcn-svelte-lab, an experimental Svelte registry, CLI, and agent workflow fork.",
	keywords: [
		"shadcn-svelte",
		"svelte components",
		"svelte ui library",
		"svelte design system",
		"tailwindcss components",
		"headless ui svelte",
		"accessible svelte components",
		"copy paste components",
		"svelte component library",
		"sveltekit components",
		"svelte 5 components",
		"svelte runes",
		"bits-ui",
		"radix svelte",
		"shadcn svelte",
		"free ui components",
		"open source components",
		"modern ui svelte",
		"typescript svelte components",
		"responsive components",
		"dark mode components",
		"form components svelte",
		"dashboard components",
		"chart components svelte",
		"svelte chart components",
	],
	links: {
		x: "https://x.com/huntabyte",
		github: "https://github.com/aihxp/shadcn-svelte",
	},
};
